# spring
spring:
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://${db.server}/DATABASE_NAME?${mysql.url-params}
      username: ${db.username}
      password: ${db.password}
# swagger
swagger:
  base-package: SBC.credit_card.web.controller
# mysql
mysql:
  url-params: useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
